name: klutter
description: A client for streaming comics from a Komga comic/manga/BD server.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.0+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.0.0
  cached_network_image: ^3.1.0
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.0
  dio_cache_interceptor_hive_store: ^3.0.1
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_secure_storage: ^4.2.0
  fullscreen: ^1.0.3
  hydrated_bloc: ^7.0.1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  path_provider: ^2.0.2
  photo_view: ^0.12.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^2.0.0
  rotated_corner_decoration: ^2.0.0
  rxdart: ^0.27.1
  sizer: ^2.0.13
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  built_value_generator: ^8.0.0
  json_serializable: ^4.1.3
  retrofit_generator: ^2.0.0

flutter_icons:
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/icon_ios.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  assets:
    - assets/images/

  uses-material-design: true
